--- !ditz.rubyforge.org,2008-03-06/project 
name: collective
version: "0.2"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: collective
- !ditz.rubyforge.org,2008-03-06/component 
  name: Quality
- !ditz.rubyforge.org,2008-03-06/component 
  name: Security
- !ditz.rubyforge.org,2008-03-06/component 
  name: Styling
releases: []

