---
# This is a sample database file for the DataMapper ORM
:development: &defaults
  :adapter: sqlite3
  :database: db/dev.sqlite3

:test:
  <<: *defaults
  :database: db/test.sqlite3

:production:
  <<: *defaults
  :database: './../shared/db/prod.sqlite3'